language: python
branches:
  only:
  - gh-pages
python:
  - "2.7"
install:
  - pip install mkdocs
  - pip install mkdocs-material
script:
  - mkdocs build --clean
after_script:
  - cd "$TRAVIS_BUILD_DIR"
  - cp CNAME site/
  - cp README.md site/
  - cd site
  - git init
  - git add .
  - git -c user.name="mengtanx" -c user.email="mengtanx@gmail.com" commit -m "Automatic Deployment - Update Docs"
  - git push -f -q "https://${GitHub_Token}@${GitHub_Ref}" master:master
  - cd "$TRAVIS_BUILD_DIR"
env:
 global:
   - GitHub_Ref: https://github.com/mengtanx/Momenta-Notes.git